export interface City {
  label: string; // "New York, US"
  timezone: string; // IANA
}

const RAW: [string, string, string][] = [
  // Americas
  ['New York', 'US', 'America/New_York'],
  ['Los Angeles', 'US', 'America/Los_Angeles'],
  ['Chicago', 'US', 'America/Chicago'],
  ['Houston', 'US', 'America/Chicago'],
  ['Phoenix', 'US', 'America/Phoenix'],
  ['Philadelphia', 'US', 'America/New_York'],
  ['San Antonio', 'US', 'America/Chicago'],
  ['San Diego', 'US', 'America/Los_Angeles'],
  ['Dallas', 'US', 'America/Chicago'],
  ['San Francisco', 'US', 'America/Los_Angeles'],
  ['Seattle', 'US', 'America/Los_Angeles'],
  ['Denver', 'US', 'America/Denver'],
  ['Boston', 'US', 'America/New_York'],
  ['Miami', 'US', 'America/New_York'],
  ['Atlanta', 'US', 'America/New_York'],
  ['Minneapolis', 'US', 'America/Chicago'],
  ['Portland', 'US', 'America/Los_Angeles'],
  ['Las Vegas', 'US', 'America/Los_Angeles'],
  ['Detroit', 'US', 'America/Detroit'],
  ['Austin', 'US', 'America/Chicago'],
  ['Nashville', 'US', 'America/Chicago'],
  ['Baltimore', 'US', 'America/New_York'],
  ['Washington DC', 'US', 'America/New_York'],
  ['Honolulu', 'US', 'Pacific/Honolulu'],
  ['Anchorage', 'US', 'America/Anchorage'],
  ['Toronto', 'CA', 'America/Toronto'],
  ['Vancouver', 'CA', 'America/Vancouver'],
  ['Montreal', 'CA', 'America/Toronto'],
  ['Calgary', 'CA', 'America/Edmonton'],
  ['Edmonton', 'CA', 'America/Edmonton'],
  ['Ottawa', 'CA', 'America/Toronto'],
  ['Winnipeg', 'CA', 'America/Winnipeg'],
  ['Halifax', 'CA', 'America/Halifax'],
  ['Mexico City', 'MX', 'America/Mexico_City'],
  ['Guadalajara', 'MX', 'America/Mexico_City'],
  ['Monterrey', 'MX', 'America/Monterrey'],
  ['Tijuana', 'MX', 'America/Tijuana'],
  ['São Paulo', 'BR', 'America/Sao_Paulo'],
  ['Rio de Janeiro', 'BR', 'America/Sao_Paulo'],
  ['Brasília', 'BR', 'America/Sao_Paulo'],
  ['Salvador', 'BR', 'America/Bahia'],
  ['Fortaleza', 'BR', 'America/Fortaleza'],
  ['Belo Horizonte', 'BR', 'America/Sao_Paulo'],
  ['Manaus', 'BR', 'America/Manaus'],
  ['Buenos Aires', 'AR', 'America/Argentina/Buenos_Aires'],
  ['Córdoba', 'AR', 'America/Argentina/Cordoba'],
  ['Rosario', 'AR', 'America/Argentina/Buenos_Aires'],
  ['Santiago', 'CL', 'America/Santiago'],
  ['Lima', 'PE', 'America/Lima'],
  ['Bogotá', 'CO', 'America/Bogota'],
  ['Medellín', 'CO', 'America/Bogota'],
  ['Caracas', 'VE', 'America/Caracas'],
  ['Quito', 'EC', 'America/Guayaquil'],
  ['La Paz', 'BO', 'America/La_Paz'],
  ['Asunción', 'PY', 'America/Asuncion'],
  ['Montevideo', 'UY', 'America/Montevideo'],
  ['Havana', 'CU', 'America/Havana'],
  ['Santo Domingo', 'DO', 'America/Santo_Domingo'],
  ['San Juan', 'PR', 'America/Puerto_Rico'],
  ['Guatemala City', 'GT', 'America/Guatemala'],
  ['San José', 'CR', 'America/Costa_Rica'],
  ['Panama City', 'PA', 'America/Panama'],
  ['Guayaquil', 'EC', 'America/Guayaquil'],

  // Europe
  ['London', 'GB', 'Europe/London'],
  ['Paris', 'FR', 'Europe/Paris'],
  ['Berlin', 'DE', 'Europe/Berlin'],
  ['Madrid', 'ES', 'Europe/Madrid'],
  ['Rome', 'IT', 'Europe/Rome'],
  ['Amsterdam', 'NL', 'Europe/Amsterdam'],
  ['Brussels', 'BE', 'Europe/Brussels'],
  ['Vienna', 'AT', 'Europe/Vienna'],
  ['Zurich', 'CH', 'Europe/Zurich'],
  ['Stockholm', 'SE', 'Europe/Stockholm'],
  ['Oslo', 'NO', 'Europe/Oslo'],
  ['Copenhagen', 'DK', 'Europe/Copenhagen'],
  ['Helsinki', 'FI', 'Europe/Helsinki'],
  ['Warsaw', 'PL', 'Europe/Warsaw'],
  ['Prague', 'CZ', 'Europe/Prague'],
  ['Budapest', 'HU', 'Europe/Budapest'],
  ['Bucharest', 'RO', 'Europe/Bucharest'],
  ['Athens', 'GR', 'Europe/Athens'],
  ['Lisbon', 'PT', 'Europe/Lisbon'],
  ['Barcelona', 'ES', 'Europe/Madrid'],
  ['Munich', 'DE', 'Europe/Berlin'],
  ['Hamburg', 'DE', 'Europe/Berlin'],
  ['Frankfurt', 'DE', 'Europe/Berlin'],
  ['Milan', 'IT', 'Europe/Rome'],
  ['Naples', 'IT', 'Europe/Rome'],
  ['Kyiv', 'UA', 'Europe/Kyiv'],
  ['Moscow', 'RU', 'Europe/Moscow'],
  ['St. Petersburg', 'RU', 'Europe/Moscow'],
  ['Novosibirsk', 'RU', 'Asia/Novosibirsk'],
  ['Yekaterinburg', 'RU', 'Asia/Yekaterinburg'],
  ['Dublin', 'IE', 'Europe/Dublin'],
  ['Edinburgh', 'GB', 'Europe/London'],
  ['Manchester', 'GB', 'Europe/London'],
  ['Birmingham', 'GB', 'Europe/London'],
  ['Lyon', 'FR', 'Europe/Paris'],
  ['Marseille', 'FR', 'Europe/Paris'],
  ['Belgrade', 'RS', 'Europe/Belgrade'],
  ['Sofia', 'BG', 'Europe/Sofia'],
  ['Zagreb', 'HR', 'Europe/Zagreb'],
  ['Riga', 'LV', 'Europe/Riga'],
  ['Vilnius', 'LT', 'Europe/Vilnius'],
  ['Tallinn', 'EE', 'Europe/Tallinn'],
  ['Bratislava', 'SK', 'Europe/Bratislava'],
  ['Ljubljana', 'SI', 'Europe/Ljubljana'],
  ['Sarajevo', 'BA', 'Europe/Sarajevo'],
  ['Skopje', 'MK', 'Europe/Skopje'],
  ['Tirana', 'AL', 'Europe/Tirane'],
  ['Minsk', 'BY', 'Europe/Minsk'],
  ['Reykjavik', 'IS', 'Atlantic/Reykjavik'],
  ['Nicosia', 'CY', 'Asia/Nicosia'],

  // Middle East & Central Asia
  ['Istanbul', 'TR', 'Europe/Istanbul'],
  ['Ankara', 'TR', 'Europe/Istanbul'],
  ['Dubai', 'AE', 'Asia/Dubai'],
  ['Abu Dhabi', 'AE', 'Asia/Dubai'],
  ['Riyadh', 'SA', 'Asia/Riyadh'],
  ['Jeddah', 'SA', 'Asia/Riyadh'],
  ['Kuwait City', 'KW', 'Asia/Kuwait'],
  ['Doha', 'QA', 'Asia/Qatar'],
  ['Manama', 'BH', 'Asia/Bahrain'],
  ['Muscat', 'OM', 'Asia/Muscat'],
  ['Tel Aviv', 'IL', 'Asia/Jerusalem'],
  ['Jerusalem', 'IL', 'Asia/Jerusalem'],
  ['Beirut', 'LB', 'Asia/Beirut'],
  ['Amman', 'JO', 'Asia/Amman'],
  ['Damascus', 'SY', 'Asia/Damascus'],
  ['Baghdad', 'IQ', 'Asia/Baghdad'],
  ['Tehran', 'IR', 'Asia/Tehran'],
  ['Baku', 'AZ', 'Asia/Baku'],
  ['Yerevan', 'AM', 'Asia/Yerevan'],
  ['Tbilisi', 'GE', 'Asia/Tbilisi'],
  ['Tashkent', 'UZ', 'Asia/Tashkent'],
  ['Almaty', 'KZ', 'Asia/Almaty'],
  ['Kabul', 'AF', 'Asia/Kabul'],

  // South & Southeast Asia
  ['Mumbai', 'IN', 'Asia/Kolkata'],
  ['Delhi', 'IN', 'Asia/Kolkata'],
  ['Bangalore', 'IN', 'Asia/Kolkata'],
  ['Hyderabad', 'IN', 'Asia/Kolkata'],
  ['Chennai', 'IN', 'Asia/Kolkata'],
  ['Kolkata', 'IN', 'Asia/Kolkata'],
  ['Ahmedabad', 'IN', 'Asia/Kolkata'],
  ['Pune', 'IN', 'Asia/Kolkata'],
  ['Karachi', 'PK', 'Asia/Karachi'],
  ['Lahore', 'PK', 'Asia/Karachi'],
  ['Islamabad', 'PK', 'Asia/Karachi'],
  ['Dhaka', 'BD', 'Asia/Dhaka'],
  ['Colombo', 'LK', 'Asia/Colombo'],
  ['Kathmandu', 'NP', 'Asia/Kathmandu'],
  ['Yangon', 'MM', 'Asia/Rangoon'],
  ['Bangkok', 'TH', 'Asia/Bangkok'],
  ['Ho Chi Minh City', 'VN', 'Asia/Ho_Chi_Minh'],
  ['Hanoi', 'VN', 'Asia/Bangkok'],
  ['Phnom Penh', 'KH', 'Asia/Phnom_Penh'],
  ['Vientiane', 'LA', 'Asia/Vientiane'],
  ['Kuala Lumpur', 'MY', 'Asia/Kuala_Lumpur'],
  ['Singapore', 'SG', 'Asia/Singapore'],
  ['Jakarta', 'ID', 'Asia/Jakarta'],
  ['Surabaya', 'ID', 'Asia/Jakarta'],
  ['Bali', 'ID', 'Asia/Makassar'],
  ['Manila', 'PH', 'Asia/Manila'],
  ['Cebu', 'PH', 'Asia/Manila'],

  // East Asia
  ['Tokyo', 'JP', 'Asia/Tokyo'],
  ['Osaka', 'JP', 'Asia/Tokyo'],
  ['Sapporo', 'JP', 'Asia/Tokyo'],
  ['Nagoya', 'JP', 'Asia/Tokyo'],
  ['Fukuoka', 'JP', 'Asia/Tokyo'],
  ['Seoul', 'KR', 'Asia/Seoul'],
  ['Busan', 'KR', 'Asia/Seoul'],
  ['Beijing', 'CN', 'Asia/Shanghai'],
  ['Shanghai', 'CN', 'Asia/Shanghai'],
  ['Guangzhou', 'CN', 'Asia/Shanghai'],
  ['Shenzhen', 'CN', 'Asia/Shanghai'],
  ['Chengdu', 'CN', 'Asia/Shanghai'],
  ['Chongqing', 'CN', 'Asia/Shanghai'],
  ['Wuhan', 'CN', 'Asia/Shanghai'],
  ['Tianjin', 'CN', 'Asia/Shanghai'],
  ['Xi\'an', 'CN', 'Asia/Shanghai'],
  ['Hangzhou', 'CN', 'Asia/Shanghai'],
  ['Nanjing', 'CN', 'Asia/Shanghai'],
  ['Hong Kong', 'HK', 'Asia/Hong_Kong'],
  ['Macau', 'MO', 'Asia/Macau'],
  ['Taipei', 'TW', 'Asia/Taipei'],
  ['Ulaanbaatar', 'MN', 'Asia/Ulaanbaatar'],

  // Africa
  ['Lagos', 'NG', 'Africa/Lagos'],
  ['Kinshasa', 'CD', 'Africa/Kinshasa'],
  ['Cairo', 'EG', 'Africa/Cairo'],
  ['Johannesburg', 'ZA', 'Africa/Johannesburg'],
  ['Cape Town', 'ZA', 'Africa/Johannesburg'],
  ['Durban', 'ZA', 'Africa/Johannesburg'],
  ['Luanda', 'AO', 'Africa/Luanda'],
  ['Nairobi', 'KE', 'Africa/Nairobi'],
  ['Dar es Salaam', 'TZ', 'Africa/Dar_es_Salaam'],
  ['Addis Ababa', 'ET', 'Africa/Addis_Ababa'],
  ['Accra', 'GH', 'Africa/Accra'],
  ['Abidjan', 'CI', 'Africa/Abidjan'],
  ['Dakar', 'SN', 'Africa/Dakar'],
  ['Casablanca', 'MA', 'Africa/Casablanca'],
  ['Algiers', 'DZ', 'Africa/Algiers'],
  ['Tunis', 'TN', 'Africa/Tunis'],
  ['Tripoli', 'LY', 'Africa/Tripoli'],
  ['Khartoum', 'SD', 'Africa/Khartoum'],
  ['Kampala', 'UG', 'Africa/Kampala'],
  ['Lusaka', 'ZM', 'Africa/Lusaka'],
  ['Harare', 'ZW', 'Africa/Harare'],
  ['Maputo', 'MZ', 'Africa/Maputo'],
  ['Antananarivo', 'MG', 'Indian/Antananarivo'],
  ['Kigali', 'RW', 'Africa/Kigali'],
  ['Douala', 'CM', 'Africa/Douala'],

  // Oceania
  ['Sydney', 'AU', 'Australia/Sydney'],
  ['Melbourne', 'AU', 'Australia/Melbourne'],
  ['Brisbane', 'AU', 'Australia/Brisbane'],
  ['Perth', 'AU', 'Australia/Perth'],
  ['Adelaide', 'AU', 'Australia/Adelaide'],
  ['Canberra', 'AU', 'Australia/Sydney'],
  ['Auckland', 'NZ', 'Pacific/Auckland'],
  ['Christchurch', 'NZ', 'Pacific/Auckland'],
  ['Wellington', 'NZ', 'Pacific/Auckland'],
  ['Suva', 'FJ', 'Pacific/Fiji'],
  ['Port Moresby', 'PG', 'Pacific/Port_Moresby'],
];

export const CITIES: City[] = RAW.map(([city, country, timezone]) => ({
  label: `${city}, ${country}`,
  timezone,
  city,
}));

export function findCityByTimezone(tz: string): City | undefined {
  return CITIES.find(c => c.timezone === tz);
}

export function filterCities(query: string): City[] {
  if (!query) return CITIES;
  const q = query.toLowerCase();
  return CITIES.filter(c => c.label.toLowerCase().includes(q));
}
